[package]
name = "rust-snake"
version = "0.1.0"
authors = ["Walter Huang <waltermwfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston = "*"
piston_window = "*"
rand = "*"
find_folder = "*"
